name: First workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "CI pipeline"

            - name: Checkout
              uses: actions/checkout@v6

            - name: List files
              run: ls
              
            - name: Read file
              run: cat ./action-1/README.md