name: Shell workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Shell permission
              run: chmod 777 ascii.sh

            - name: Execute shell script
              run: ./ascii.sh

