name: Workflow filters
on:
    push:
        branches:
            - main
            - '!feature/*'      # ! ignores running a workflow in the specified branch

    pull_request: 
        types:
            - opened
            - closed
        paths-ignore:           # ignores running the workflow if the changes are made in the path specified
            - README.md                     
        branches:
            -main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Run docker image
              run: docker run hello-world            
            